server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: portfolio-service
              uri: lb://portfolio-service
              predicates:
                - Path=/api/portfolio/**

            - id: wealth-service
              uri: lb://wealth-service
              predicates:
                - Path=/app/wealthcalulater/**
        default-filters:
        - PreserveHostHeader
        - AddRequestHeader=Cookie, ${originalRequest.cookies}
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true    

        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance-id: ${spring.application.name}:${server.port}

  instance:
    prefer-ip-address: true
    
    
    
